name: Rust

on:
  push:
  pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: editorconfig-checker

